# Generated by Django 2.1.7 on 2020-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('rmse', models.FloatField()),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Waterquality',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('ph', models.FloatField(blank=True, db_column='PH', null=True)),
                ('do', models.FloatField(blank=True, db_column='DO', null=True)),
                ('nh3n', models.FloatField(blank=True, db_column='NH3N', null=True)),
                ('waterTemperature', models.FloatField(blank=True, db_column='WaterTemperature', null=True)),
                ('date', models.DateTimeField()),
                ('station', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WaterQuality',
            },
        ),
    ]
